---
name: Import Issues

on:
  push:
    paths:
      - 'src/data/issues/**'
    branches:
      - main
      - master
  workflow_dispatch:

permissions:
  contents: write
  issues: write

jobs:
  find-files:
    runs-on: ubuntu-latest
    outputs:
      files: ${{ steps.find-files.outputs.files }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Find issue definition files
        id: find-files
        run: |
          files=()
          for file in src/data/issues/*.{yml,yaml,csv}; do
            # Skip if no files match the pattern
            [ -f "$file" ] || continue

            # Skip README and other non-issue files
            basename_file=$(basename "$file")
            if [[ "$basename_file" == "README"* ]]; then
              echo "Skipping $file (README file)"
              continue
            fi

            # Determine file format based on extension
            if [[ "$file" == *.yml ]] || [[ "$file" == *.yaml ]]; then
              format="yaml"
            elif [[ "$file" == *.csv ]]; then
              format="csv"
            else
              echo "Unknown file format for $file, skipping"
              continue
            fi

            echo "Found $file with format: $format"
            files+=("{\"file\":\"$file\",\"format\":\"$format\"}")
          done

          # Convert array to JSON
          json_array=$(printf '%s,' "${files[@]}" | sed 's/,$//')
          echo "files=[$json_array]" >> $GITHUB_OUTPUT

  import-issues:
    needs: find-files
    runs-on: ubuntu-latest
    if: needs.find-files.outputs.files != '[]'
    strategy:
      matrix:
        include: ${{ fromJson(needs.find-files.outputs.files) }}
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Import issues from ${{ matrix.file }}
        uses: dsanchezcr/issue-importer-action@v1
        with:
          file-path: ${{ matrix.file }}
          file-format: ${{ matrix.format }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

  commit-changes:
    needs: [find-files, import-issues]
    runs-on: ubuntu-latest
    if: always() && needs.find-files.outputs.files != '[]'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit updated issue definition files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add src/data/issues/
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update issue definition files after import [skip ci]"
            git push
